In [135]:
import numpy as np # type: ignore

### **1. Desarrollar un código en Jupyter Notebook que trabaje con arrays y realice varias operaciones matemáticas y de manipulación de datos. El programa debe obtener la mediana, el promedio, y las posiciones de los valores máximo y mínimo de un array. Además, deberá transformar el array en una matriz y utilizar las funciones específicas para ello. A continuación se detalla los requerimientos:**


<h5>A.- Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos del 1 al 10. Este array no debe ser aleatorio<h5/>

In [136]:
array1 = np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h5>B.- Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores deben ser enteros entre el 1 al 20.<h5/>

In [137]:
array2 = np.random.randint(1,21,10)
array2

array([ 3, 14,  9,  2,  1, 12,  1, 19, 11, 14])

<h5>C.- Obtener un vector único de 10 elementos, sumando los dos arrays anteriores.<h5/>

In [138]:
vector = array1 + array2
vector

array([ 4, 16, 12,  6,  6, 18,  8, 27, 20, 24])

<h5>D.- Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV.<h5/>

141

<h5>E.- Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando las funciones vistas en la Unidad IV. Tomar el vector de la letra D. E. Transformar el vector obtenido en una Matriz de 2 x 5<h5/>

In [153]:
# Mediana
vector_mediana = np.median(vector)
vector_mediana

14.0

In [140]:

# Promedio
vector_promedio = np.mean(vector)
vector_promedio

14.1

In [141]:
# Posición de Valor Máximo
vector_posmax = np.argmax(vector)
vector_posmax

7

In [142]:
# Posición de Valor Mínimo
vector_posmin = np.argmin(vector)
vector_posmin

0

In [143]:
vector_total = vector_promedio + vector_posmax + vector_posmin
vector_total

21.1

In [144]:
matriz = vector.reshape(2,5)
matriz

array([[ 4, 16, 12,  6,  6],
       [18,  8, 27, 20, 24]])