#### **IMPORTANDO LIBRERÍA NUMPY**

In [5]:
#Importante ejecutar primero el "import", al contrario podría salir error en los códigos
import numpy as np

#### Creando una lista de 10 elementos

In [10]:
lista = list(range(1, 11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformación de una lista a un Array

In [11]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Corroborando el tipo de estructura

In [12]:
type(arreglo)

numpy.ndarray

#### Corroborando el tipo de datos del arreglo

In [13]:
arreglo.dtype

dtype('int32')

#### Definiendo el Array de int32 a float32

In [15]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### SIgue siendo un Array de int32

In [16]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Transformación de datos de int32 a float32

In [17]:
# Arreglos soportan un solo tipo de datos
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

<h4 style = "color>

<h2 style = "color:blue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h2>
<h4 style = "color:cyan">Obteniendo el promedio de Array</h3>

In [18]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:cyan">Obteniendo la mediana del Array</h3>

In [19]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:cyan">Desviación estándar del arreglo</h3>

In [20]:
desviación_std = np.std(arreglo)
desviación_std

2.8722813232690143

<h4 style = "color:cyan">Generación de un arreglo de 10 elementos de solamente números "uno"</h3>

In [21]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:cyan">Generación de un arreglo de 10 elementos de solamente números "cero"</h3>

In [23]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h2 style = "color:green"><b>UTILIZANDO LA FUNCIÓN RANDOM</b></h2>
<h4 style = "color:lightgreen">Generando arreglo aleatorio de 5 números</h3>

In [25]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.87652996, 0.63759834, 0.78202163, 0.45281869, 0.20554601,
       0.57352438, 0.70868038, 0.85211929, 0.80620269, 0.23846974])

<h4 style = "color:lightgreen">Generando una matriz aleatoria 3x3</h3>

In [3]:
matriz = np.random.rand(3,3)
matriz

array([[0.68291584, 0.11803137, 0.42414292],
       [0.56026059, 0.40893732, 0.2962695 ],
       [0.58578649, 0.1975407 , 0.78648266]])

<h4 style = "color:lightgreen">Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h3>

In [30]:
arreglo_aleatorio2 = np.random.randint(1,1001,0)
arreglo_aleatorio2

array([], dtype=int32)